"""ACES 2065-1 delivery for RUDRA (torch-free).

Writes SMPTE ST 2065-4 ACES container EXRs (AP0 primaries, ACES white,
half-float, chromaticities attribute present) from RUDRA's Rec.2020
diffuse-white-relative scene linear, and generates a minimal OCIO v2 config
so Resolve/Nuke/Flame pick the working space up by name instead of by folklore.

Exposure convention (documented, load-bearing): RUDRA scene linear anchors
18% grey at 0.18 and diffuse white at 1.0 — the same mid-grey anchor as ACES.
Rec.2020 -> AP0 is therefore ONLY a primaries/white-point matrix; pixel
magnitudes carry over unchanged. ``exposure_scale`` exists for deliberate
re-anchoring and defaults to 1.0.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .colorspace import (AP0_CHROMATICITIES, AP1_CHROMATICITIES, convert,
                         rgb_to_rgb_matrix)
from .exr import write_exr

__all__ = ["write_aces_exr", "write_acescg_exr", "generate_ocio_config"]


def write_aces_exr(
    rgb_linear: np.ndarray,
    path: str | Path,
    source_space: str = "rec2020",
    exposure_scale: float = 1.0,
    provenance: dict | None = None,
) -> Path:
    """Write an (H, W, 3) linear frame as an ACES 2065-1 container EXR.

    Args:
        rgb_linear: scene-linear RGB in ``source_space``, diffuse white = 1.0.
        source_space: 'rec2020' (RUDRA default), 'rec709', or 'p3d65'.
        exposure_scale: multiply before conversion (1.0 = shared 0.18 anchor).
        provenance: extra key/values recorded as string attributes.
    """
    aces = convert(np.asarray(rgb_linear, dtype=np.float32) * float(exposure_scale),
                   source_space, "ap0")
    attrs = {
        "acesImageContainerFlag": "1",
        "rudra:sourceSpace": source_space,
        "rudra:exposureConvention": "0.18 = 18% grey (scene), diffuse white = 1.0",
        "rudra:exposureScale": repr(float(exposure_scale)),
    }
    if provenance:
        attrs["rudra:provenance"] = json.dumps(provenance, sort_keys=True)
    return write_exr(path, aces, half=True, chromaticities=AP0_CHROMATICITIES, attributes=attrs)


def write_acescg_exr(
    rgb_linear: np.ndarray,
    path: str | Path,
    source_space: str = "rec2020",
    exposure_scale: float = 1.0,
    provenance: dict | None = None,
) -> Path:
    """Write an (H, W, 3) linear frame as an ACEScg (AP1) EXR.

    Same maths as the AP0 container, a different primary set. AP0 is the
    archival wrapper; AP1 is the space a comp is actually built in, so a
    pipeline handed AP0 usually converts straight out of it. Offering both
    saves that round trip and matches what competing tools emit.
    """
    cg = convert(np.asarray(rgb_linear, dtype=np.float32) * float(exposure_scale),
                 source_space, "ap1")
    attrs = {
        "rudra:container": "ACEScg (AP1)",
        "rudra:sourceSpace": source_space,
        "rudra:exposureConvention": "0.18 = 18% grey (scene), diffuse white = 1.0",
        "rudra:exposureScale": repr(float(exposure_scale)),
    }
    if provenance:
        attrs["rudra:provenance"] = json.dumps(provenance, sort_keys=True)
    return write_exr(path, cg, half=True, chromaticities=AP1_CHROMATICITIES,
                     attributes=attrs)


def _matrix_yaml(matrix: np.ndarray, indent: int = 8) -> str:
    """4x4 row-major OCIO matrix string from a 3x3."""
    m4 = np.eye(4)
    m4[:3, :3] = matrix
    values = ", ".join(f"{v:.10f}" for v in m4.flatten())
    return " " * indent + f"- !<MatrixTransform> {{matrix: [{values}]}}"


def generate_ocio_config(path: str | Path) -> Path:
    """Write a minimal OCIO v2 config with RUDRA's spaces defined exactly.

    Scene spaces (matrix-exact, verified by the delivery test suite):
      - ACES2065-1 (AP0)          — reference
      - ACEScg (AP1)
      - RUDRA Scene Linear (Rec.2020, diffuse white = 1.0)
      - Linear Rec.709

    Display transforms are intentionally NOT invented here: pair this config
    with the official ACES OCIO config for output transforms. This file's job
    is to make RUDRA's working space a named, exact citizen of the pipeline.
    """
    to_ref = {
        "RUDRA Scene Linear (Rec.2020)": rgb_to_rgb_matrix("rec2020", "ap0"),
        "Linear Rec.709": rgb_to_rgb_matrix("rec709", "ap0"),
        "ACEScg": rgb_to_rgb_matrix("ap1", "ap0"),
    }
    blocks = []
    for name, matrix in to_ref.items():
        blocks.append(
            f"""  - !<ColorSpace>
    name: {name}
    family: Scene
    encoding: scene-linear
    bitdepth: 32f
    description: |
      Linear {name.split('(')[-1].rstrip(')') if '(' in name else name} to ACES2065-1 via Bradford CAT.
      Generated by rudra.delivery.aces; matrices derived from primaries, not copied.
    to_scene_reference: !<GroupTransform>
      children:
{_matrix_yaml(matrix)}
""")
    config = f"""ocio_profile_version: 2

description: RUDRA delivery working spaces (pair with the official ACES OCIO config for display transforms)
name: rudra-delivery

roles:
  scene_linear: RUDRA Scene Linear (Rec.2020)
  aces_interchange: ACES2065-1
  default: RUDRA Scene Linear (Rec.2020)
  data: Raw

file_rules:
  - !<Rule> {{name: Default, colorspace: default}}

colorspaces:
  - !<ColorSpace>
    name: ACES2065-1
    family: Scene
    encoding: scene-linear
    bitdepth: 32f
    description: SMPTE ST 2065-1 AP0 primaries, ACES white. Reference space.

  - !<ColorSpace>
    name: Raw
    family: Utility
    encoding: data
    isdata: true

{"".join(blocks)}"""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(config, encoding="utf-8")
    return path
